// Контакты и адрес сайта берутся из env (NEXT_PUBLIC_* инлайнится при сборке),
// чтобы почту/телеграм можно было поменять без правки кода — только .env + rebuild.
export const SITE = {
  name: "VERH",
  legalName: "VERH Studio",
  url: process.env.NEXT_PUBLIC_SITE_URL ?? "https://verh.tech",
  locale: "ru_RU",
  language: "ru",
  founded: "2024",
  email: process.env.NEXT_PUBLIC_CONTACT_EMAIL ?? "hi@verh.tech",
  telegram: process.env.NEXT_PUBLIC_TELEGRAM_URL ?? "https://t.me/verh_studio",
  telegramHandle: process.env.NEXT_PUBLIC_TELEGRAM_HANDLE ?? "@verh_studio",
  city: "Москва",
  region: "Москва",
  country: "RU",
  countryName: "Россия",
  timezone: "Europe/Moscow",
  founder: "Иван Жуков",
  team: [
    {
      name: "Иван",
      full: "Иван Жуков",
      initials: "ИЖ",
      role: "Сооснователь · разработка и техлид",
      photo: "/team/ivan.jpg",
      bio: "Превращает макеты в быстрый, чистый код на Next.js. Отвечает за скорость, анимацию и то, чтобы всё работало годами без костылей.",
      focus: ["Next.js", "Motion", "Performance"],
    },
    {
      name: "Илья",
      full: "Илья",
      initials: "И",
      role: "Сооснователь · дизайн и арт-дирекшн",
      photo: "/team/ilya.jpg",
      bio: "Ведёт проект от стратегии до последнего пикселя макета. Отвечает за то, чтобы сайт продавал, а не просто нравился.",
      focus: ["Стратегия", "UI/UX", "Арт-дирекшн"],
    },
  ],
  tagline: "Небольшая студия: сайты, боты и веб-приложения",
  // ≤160 символов — не обрезается в сниппете, точное вхождение «разработка сайтов»
  description:
    "VERH — небольшая веб-студия из Москвы. Разработка сайтов, лендингов и веб-приложений, Telegram-боты и AI-сервисы. Дизайн и код в одних руках, от идеи до прода.",
  shortDescription:
    "Небольшая студия из Москвы: сайты, лендинги, веб-приложения, Telegram-боты и AI-сервисы. Дизайн и код в одних руках.",
  keywords: [
    "разработка сайтов",
    "создание сайтов",
    "веб-студия",
    "веб студия москва",
    "разработка сайтов на заказ",
    "заказать сайт",
    "разработка лендингов",
    "создание лендинга",
    "разработка telegram ботов",
    "telegram mini apps",
    "чат-бот для бизнеса",
    "ai интеграция",
    "разработка веб-приложений",
    "корпоративный сайт",
    "сайт под ключ",
    "разработка сайтов next.js",
    "брендинг и сайт",
    "веб-студия москва",
    "разработка сайтов москва",
    "сайт для бизнеса",
    "редизайн сайта",
    "ui ux дизайн сайта",
    "studio web design",
    "verh studio",
  ],
  socials: {
    telegram: "https://t.me/verh_studio",
  },
  priceRange: "₽₽₽",
} as const;

export const NAV_LINKS = [
  { href: "#work", label: "Работы" },
  { href: "#services", label: "Услуги" },
  { href: "#about", label: "Студия" },
  { href: "#faq", label: "FAQ" },
  { href: "#contact", label: "Связаться" },
] as const;
